### ISSUE TITLE
Files with no line terminators, do not paste

### ISSUE THREAD

**Issue by jcwils** [BarbUk/dotfiles#3]
Any files in ~/.snippy with no line terminators do not paste
You can check files for line terminators using:
file "file.txt"
You can convert the files to have line terminators using:
sed -i -e '$a\' "file.txt"
Or convert all files using:
find -type f -print0 | xargs -0 -I {} sed -i -e '$a\' "{}"
These commands will not add multiple line terminators, if one already exists, so they're safe to use repeatedly

**Comment by BarbUk** [comment]
Good catch.
The `bashdown_simple` function was the culprit.

A fix was pushed in 0159b15

**Comment by jcwils** [comment]
Thanks. That's great

Jonathan
