### ISSUE TITLE
snippy not pasting

### ISSUE THREAD

**Issue by verajosemanuel** [BarbUk/dotfiles#4]
Hi BarbUk
I would love to use your snippy tool but after installing and configuring (created some snippets) I can fire it and choose any but nothing is pasted.
I've tried your recommendation from code:
` if nothing happens, try "xdotool click 2", "xdotool key ctrl+v" or "xdotool key ctrl+shift+v"`
no success so far.

any other hint?

Thanks in advance

**Comment by BarbUk** [comment]
Hi,

In what application are you trying to paste ?
If it's a terminal, it's probably not detected correctly.

I just pushed a small fix to handle slow focus (when pasting a snippet in chrome for example).
Could you please pull the new version and test ?

If nothing is pasted, please use the following command to create a test snippet :

```
echo '$(echo "testing snippy paste")' > ~/.config/snippy/test
```

And generate a trace with:
```
bash -x /usr/bin/snippy
```

**Comment by BarbUk** [comment]
Closing this issue (no response for several month)
